/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/PilatesAndroidNewsFeed.html

#include <gtest/gtest.h>
#include <pilates/Pilates.h>

TEST(PilatesTest, android_news_feed) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignContent(root, PilatesAlignStretch);
  PilatesNodeStyleSetWidth(root, 1080);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child0_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignContent(root_child0_child0, PilatesAlignStretch);
  PilatesNodeInsertChild(root_child0, root_child0_child0, 0);

  const PilatesNodeRef root_child0_child0_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignContent(root_child0_child0_child0, PilatesAlignStretch);
  PilatesNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);

  const PilatesNodeRef root_child0_child0_child0_child0 =
      PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(
      root_child0_child0_child0_child0, PilatesFlexDirectionRow);
  PilatesNodeStyleSetAlignContent(root_child0_child0_child0_child0, PilatesAlignStretch);
  PilatesNodeStyleSetAlignItems(root_child0_child0_child0_child0, PilatesAlignFlexStart);
  PilatesNodeStyleSetMargin(root_child0_child0_child0_child0, PilatesEdgeStart, 36);
  PilatesNodeStyleSetMargin(root_child0_child0_child0_child0, PilatesEdgeTop, 24);
  PilatesNodeInsertChild(
      root_child0_child0_child0, root_child0_child0_child0_child0, 0);

  const PilatesNodeRef root_child0_child0_child0_child0_child0 =
      PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(
      root_child0_child0_child0_child0_child0, PilatesFlexDirectionRow);
  PilatesNodeStyleSetAlignContent(
      root_child0_child0_child0_child0_child0, PilatesAlignStretch);
  PilatesNodeInsertChild(
      root_child0_child0_child0_child0,
      root_child0_child0_child0_child0_child0,
      0);

  const PilatesNodeRef root_child0_child0_child0_child0_child0_child0 =
      PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignContent(
      root_child0_child0_child0_child0_child0_child0, PilatesAlignStretch);
  PilatesNodeStyleSetWidth(root_child0_child0_child0_child0_child0_child0, 120);
  PilatesNodeStyleSetHeight(root_child0_child0_child0_child0_child0_child0, 120);
  PilatesNodeInsertChild(
      root_child0_child0_child0_child0_child0,
      root_child0_child0_child0_child0_child0_child0,
      0);

  const PilatesNodeRef root_child0_child0_child0_child0_child1 =
      PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignContent(
      root_child0_child0_child0_child0_child1, PilatesAlignStretch);
  PilatesNodeStyleSetFlexShrink(root_child0_child0_child0_child0_child1, 1);
  PilatesNodeStyleSetMargin(
      root_child0_child0_child0_child0_child1, PilatesEdgeRight, 36);
  PilatesNodeStyleSetPadding(
      root_child0_child0_child0_child0_child1, PilatesEdgeLeft, 36);
  PilatesNodeStyleSetPadding(root_child0_child0_child0_child0_child1, PilatesEdgeTop, 21);
  PilatesNodeStyleSetPadding(
      root_child0_child0_child0_child0_child1, PilatesEdgeRight, 36);
  PilatesNodeStyleSetPadding(
      root_child0_child0_child0_child0_child1, PilatesEdgeBottom, 18);
  PilatesNodeInsertChild(
      root_child0_child0_child0_child0,
      root_child0_child0_child0_child0_child1,
      1);

  const PilatesNodeRef root_child0_child0_child0_child0_child1_child0 =
      PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(
      root_child0_child0_child0_child0_child1_child0, PilatesFlexDirectionRow);
  PilatesNodeStyleSetAlignContent(
      root_child0_child0_child0_child0_child1_child0, PilatesAlignStretch);
  PilatesNodeStyleSetFlexShrink(root_child0_child0_child0_child0_child1_child0, 1);
  PilatesNodeInsertChild(
      root_child0_child0_child0_child0_child1,
      root_child0_child0_child0_child0_child1_child0,
      0);

  const PilatesNodeRef root_child0_child0_child0_child0_child1_child1 =
      PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignContent(
      root_child0_child0_child0_child0_child1_child1, PilatesAlignStretch);
  PilatesNodeStyleSetFlexShrink(root_child0_child0_child0_child0_child1_child1, 1);
  PilatesNodeInsertChild(
      root_child0_child0_child0_child0_child1,
      root_child0_child0_child0_child0_child1_child1,
      1);

  const PilatesNodeRef root_child0_child0_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignContent(root_child0_child0_child1, PilatesAlignStretch);
  PilatesNodeInsertChild(root_child0_child0, root_child0_child0_child1, 1);

  const PilatesNodeRef root_child0_child0_child1_child0 =
      PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(
      root_child0_child0_child1_child0, PilatesFlexDirectionRow);
  PilatesNodeStyleSetAlignContent(root_child0_child0_child1_child0, PilatesAlignStretch);
  PilatesNodeStyleSetAlignItems(root_child0_child0_child1_child0, PilatesAlignFlexStart);
  PilatesNodeStyleSetMargin(root_child0_child0_child1_child0, PilatesEdgeStart, 174);
  PilatesNodeStyleSetMargin(root_child0_child0_child1_child0, PilatesEdgeTop, 24);
  PilatesNodeInsertChild(
      root_child0_child0_child1, root_child0_child0_child1_child0, 0);

  const PilatesNodeRef root_child0_child0_child1_child0_child0 =
      PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(
      root_child0_child0_child1_child0_child0, PilatesFlexDirectionRow);
  PilatesNodeStyleSetAlignContent(
      root_child0_child0_child1_child0_child0, PilatesAlignStretch);
  PilatesNodeInsertChild(
      root_child0_child0_child1_child0,
      root_child0_child0_child1_child0_child0,
      0);

  const PilatesNodeRef root_child0_child0_child1_child0_child0_child0 =
      PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignContent(
      root_child0_child0_child1_child0_child0_child0, PilatesAlignStretch);
  PilatesNodeStyleSetWidth(root_child0_child0_child1_child0_child0_child0, 72);
  PilatesNodeStyleSetHeight(root_child0_child0_child1_child0_child0_child0, 72);
  PilatesNodeInsertChild(
      root_child0_child0_child1_child0_child0,
      root_child0_child0_child1_child0_child0_child0,
      0);

  const PilatesNodeRef root_child0_child0_child1_child0_child1 =
      PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignContent(
      root_child0_child0_child1_child0_child1, PilatesAlignStretch);
  PilatesNodeStyleSetFlexShrink(root_child0_child0_child1_child0_child1, 1);
  PilatesNodeStyleSetMargin(
      root_child0_child0_child1_child0_child1, PilatesEdgeRight, 36);
  PilatesNodeStyleSetPadding(
      root_child0_child0_child1_child0_child1, PilatesEdgeLeft, 36);
  PilatesNodeStyleSetPadding(root_child0_child0_child1_child0_child1, PilatesEdgeTop, 21);
  PilatesNodeStyleSetPadding(
      root_child0_child0_child1_child0_child1, PilatesEdgeRight, 36);
  PilatesNodeStyleSetPadding(
      root_child0_child0_child1_child0_child1, PilatesEdgeBottom, 18);
  PilatesNodeInsertChild(
      root_child0_child0_child1_child0,
      root_child0_child0_child1_child0_child1,
      1);

  const PilatesNodeRef root_child0_child0_child1_child0_child1_child0 =
      PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(
      root_child0_child0_child1_child0_child1_child0, PilatesFlexDirectionRow);
  PilatesNodeStyleSetAlignContent(
      root_child0_child0_child1_child0_child1_child0, PilatesAlignStretch);
  PilatesNodeStyleSetFlexShrink(root_child0_child0_child1_child0_child1_child0, 1);
  PilatesNodeInsertChild(
      root_child0_child0_child1_child0_child1,
      root_child0_child0_child1_child0_child1_child0,
      0);

  const PilatesNodeRef root_child0_child0_child1_child0_child1_child1 =
      PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignContent(
      root_child0_child0_child1_child0_child1_child1, PilatesAlignStretch);
  PilatesNodeStyleSetFlexShrink(root_child0_child0_child1_child0_child1_child1, 1);
  PilatesNodeInsertChild(
      root_child0_child0_child1_child0_child1,
      root_child0_child0_child1_child0_child1_child1,
      1);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(1080, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(240, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(1080, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(240, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(1080, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(240, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(1080, PilatesNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(144, PilatesNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(36, PilatesNodeLayoutGetLeft(root_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(24, PilatesNodeLayoutGetTop(root_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(1044, PilatesNodeLayoutGetWidth(root_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(120, PilatesNodeLayoutGetHeight(root_child0_child0_child0_child0));

  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetLeft(root_child0_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetTop(root_child0_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      120, PilatesNodeLayoutGetWidth(root_child0_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      120, PilatesNodeLayoutGetHeight(root_child0_child0_child0_child0_child0));

  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetLeft(root_child0_child0_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetTop(root_child0_child0_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      120,
      PilatesNodeLayoutGetWidth(root_child0_child0_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      120,
      PilatesNodeLayoutGetHeight(root_child0_child0_child0_child0_child0_child0));

  ASSERT_FLOAT_EQ(
      120, PilatesNodeLayoutGetLeft(root_child0_child0_child0_child0_child1));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetTop(root_child0_child0_child0_child0_child1));
  ASSERT_FLOAT_EQ(
      72, PilatesNodeLayoutGetWidth(root_child0_child0_child0_child0_child1));
  ASSERT_FLOAT_EQ(
      39, PilatesNodeLayoutGetHeight(root_child0_child0_child0_child0_child1));

  ASSERT_FLOAT_EQ(
      36, PilatesNodeLayoutGetLeft(root_child0_child0_child0_child0_child1_child0));
  ASSERT_FLOAT_EQ(
      21, PilatesNodeLayoutGetTop(root_child0_child0_child0_child0_child1_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetWidth(root_child0_child0_child0_child0_child1_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetHeight(root_child0_child0_child0_child0_child1_child0));

  ASSERT_FLOAT_EQ(
      36, PilatesNodeLayoutGetLeft(root_child0_child0_child0_child0_child1_child1));
  ASSERT_FLOAT_EQ(
      21, PilatesNodeLayoutGetTop(root_child0_child0_child0_child0_child1_child1));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetWidth(root_child0_child0_child0_child0_child1_child1));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetHeight(root_child0_child0_child0_child0_child1_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0_child1));
  ASSERT_FLOAT_EQ(144, PilatesNodeLayoutGetTop(root_child0_child0_child1));
  ASSERT_FLOAT_EQ(1080, PilatesNodeLayoutGetWidth(root_child0_child0_child1));
  ASSERT_FLOAT_EQ(96, PilatesNodeLayoutGetHeight(root_child0_child0_child1));

  ASSERT_FLOAT_EQ(174, PilatesNodeLayoutGetLeft(root_child0_child0_child1_child0));
  ASSERT_FLOAT_EQ(24, PilatesNodeLayoutGetTop(root_child0_child0_child1_child0));
  ASSERT_FLOAT_EQ(906, PilatesNodeLayoutGetWidth(root_child0_child0_child1_child0));
  ASSERT_FLOAT_EQ(72, PilatesNodeLayoutGetHeight(root_child0_child0_child1_child0));

  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetLeft(root_child0_child0_child1_child0_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetTop(root_child0_child0_child1_child0_child0));
  ASSERT_FLOAT_EQ(
      72, PilatesNodeLayoutGetWidth(root_child0_child0_child1_child0_child0));
  ASSERT_FLOAT_EQ(
      72, PilatesNodeLayoutGetHeight(root_child0_child0_child1_child0_child0));

  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetLeft(root_child0_child0_child1_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetTop(root_child0_child0_child1_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      72, PilatesNodeLayoutGetWidth(root_child0_child0_child1_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      72,
      PilatesNodeLayoutGetHeight(root_child0_child0_child1_child0_child0_child0));

  ASSERT_FLOAT_EQ(
      72, PilatesNodeLayoutGetLeft(root_child0_child0_child1_child0_child1));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetTop(root_child0_child0_child1_child0_child1));
  ASSERT_FLOAT_EQ(
      72, PilatesNodeLayoutGetWidth(root_child0_child0_child1_child0_child1));
  ASSERT_FLOAT_EQ(
      39, PilatesNodeLayoutGetHeight(root_child0_child0_child1_child0_child1));

  ASSERT_FLOAT_EQ(
      36, PilatesNodeLayoutGetLeft(root_child0_child0_child1_child0_child1_child0));
  ASSERT_FLOAT_EQ(
      21, PilatesNodeLayoutGetTop(root_child0_child0_child1_child0_child1_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetWidth(root_child0_child0_child1_child0_child1_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetHeight(root_child0_child0_child1_child0_child1_child0));

  ASSERT_FLOAT_EQ(
      36, PilatesNodeLayoutGetLeft(root_child0_child0_child1_child0_child1_child1));
  ASSERT_FLOAT_EQ(
      21, PilatesNodeLayoutGetTop(root_child0_child0_child1_child0_child1_child1));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetWidth(root_child0_child0_child1_child0_child1_child1));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetHeight(root_child0_child0_child1_child0_child1_child1));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(1080, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(240, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(1080, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(240, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(1080, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(240, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(1080, PilatesNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(144, PilatesNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(24, PilatesNodeLayoutGetTop(root_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(1044, PilatesNodeLayoutGetWidth(root_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(120, PilatesNodeLayoutGetHeight(root_child0_child0_child0_child0));

  ASSERT_FLOAT_EQ(
      924, PilatesNodeLayoutGetLeft(root_child0_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetTop(root_child0_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      120, PilatesNodeLayoutGetWidth(root_child0_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      120, PilatesNodeLayoutGetHeight(root_child0_child0_child0_child0_child0));

  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetLeft(root_child0_child0_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetTop(root_child0_child0_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      120,
      PilatesNodeLayoutGetWidth(root_child0_child0_child0_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      120,
      PilatesNodeLayoutGetHeight(root_child0_child0_child0_child0_child0_child0));

  ASSERT_FLOAT_EQ(
      816, PilatesNodeLayoutGetLeft(root_child0_child0_child0_child0_child1));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetTop(root_child0_child0_child0_child0_child1));
  ASSERT_FLOAT_EQ(
      72, PilatesNodeLayoutGetWidth(root_child0_child0_child0_child0_child1));
  ASSERT_FLOAT_EQ(
      39, PilatesNodeLayoutGetHeight(root_child0_child0_child0_child0_child1));

  ASSERT_FLOAT_EQ(
      36, PilatesNodeLayoutGetLeft(root_child0_child0_child0_child0_child1_child0));
  ASSERT_FLOAT_EQ(
      21, PilatesNodeLayoutGetTop(root_child0_child0_child0_child0_child1_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetWidth(root_child0_child0_child0_child0_child1_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetHeight(root_child0_child0_child0_child0_child1_child0));

  ASSERT_FLOAT_EQ(
      36, PilatesNodeLayoutGetLeft(root_child0_child0_child0_child0_child1_child1));
  ASSERT_FLOAT_EQ(
      21, PilatesNodeLayoutGetTop(root_child0_child0_child0_child0_child1_child1));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetWidth(root_child0_child0_child0_child0_child1_child1));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetHeight(root_child0_child0_child0_child0_child1_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0_child1));
  ASSERT_FLOAT_EQ(144, PilatesNodeLayoutGetTop(root_child0_child0_child1));
  ASSERT_FLOAT_EQ(1080, PilatesNodeLayoutGetWidth(root_child0_child0_child1));
  ASSERT_FLOAT_EQ(96, PilatesNodeLayoutGetHeight(root_child0_child0_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0_child1_child0));
  ASSERT_FLOAT_EQ(24, PilatesNodeLayoutGetTop(root_child0_child0_child1_child0));
  ASSERT_FLOAT_EQ(906, PilatesNodeLayoutGetWidth(root_child0_child0_child1_child0));
  ASSERT_FLOAT_EQ(72, PilatesNodeLayoutGetHeight(root_child0_child0_child1_child0));

  ASSERT_FLOAT_EQ(
      834, PilatesNodeLayoutGetLeft(root_child0_child0_child1_child0_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetTop(root_child0_child0_child1_child0_child0));
  ASSERT_FLOAT_EQ(
      72, PilatesNodeLayoutGetWidth(root_child0_child0_child1_child0_child0));
  ASSERT_FLOAT_EQ(
      72, PilatesNodeLayoutGetHeight(root_child0_child0_child1_child0_child0));

  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetLeft(root_child0_child0_child1_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetTop(root_child0_child0_child1_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      72, PilatesNodeLayoutGetWidth(root_child0_child0_child1_child0_child0_child0));
  ASSERT_FLOAT_EQ(
      72,
      PilatesNodeLayoutGetHeight(root_child0_child0_child1_child0_child0_child0));

  ASSERT_FLOAT_EQ(
      726, PilatesNodeLayoutGetLeft(root_child0_child0_child1_child0_child1));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetTop(root_child0_child0_child1_child0_child1));
  ASSERT_FLOAT_EQ(
      72, PilatesNodeLayoutGetWidth(root_child0_child0_child1_child0_child1));
  ASSERT_FLOAT_EQ(
      39, PilatesNodeLayoutGetHeight(root_child0_child0_child1_child0_child1));

  ASSERT_FLOAT_EQ(
      36, PilatesNodeLayoutGetLeft(root_child0_child0_child1_child0_child1_child0));
  ASSERT_FLOAT_EQ(
      21, PilatesNodeLayoutGetTop(root_child0_child0_child1_child0_child1_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetWidth(root_child0_child0_child1_child0_child1_child0));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetHeight(root_child0_child0_child1_child0_child1_child0));

  ASSERT_FLOAT_EQ(
      36, PilatesNodeLayoutGetLeft(root_child0_child0_child1_child0_child1_child1));
  ASSERT_FLOAT_EQ(
      21, PilatesNodeLayoutGetTop(root_child0_child0_child1_child0_child1_child1));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetWidth(root_child0_child0_child1_child0_child1_child1));
  ASSERT_FLOAT_EQ(
      0, PilatesNodeLayoutGetHeight(root_child0_child0_child1_child0_child1_child1));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}
