/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/PilatesJustifyContentTest.html

#include <gtest/gtest.h>
#include <pilates/Pilates.h>

TEST(PilatesTest, justify_content_row_flex_start) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetWidth(root, 102);
  PilatesNodeStyleSetHeight(root, 102);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(92, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(82, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(72, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_row_flex_end) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyFlexEnd);
  PilatesNodeStyleSetWidth(root, 102);
  PilatesNodeStyleSetHeight(root, 102);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(72, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(82, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(92, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_row_center) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetWidth(root, 102);
  PilatesNodeStyleSetHeight(root, 102);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(36, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(56, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(56, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(36, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_row_space_between) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifySpaceBetween);
  PilatesNodeStyleSetWidth(root, 102);
  PilatesNodeStyleSetHeight(root, 102);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(92, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(92, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_row_space_around) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifySpaceAround);
  PilatesNodeStyleSetWidth(root, 102);
  PilatesNodeStyleSetHeight(root, 102);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(12, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(12, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_column_flex_start) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root, 102);
  PilatesNodeStyleSetHeight(root, 102);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_column_flex_end) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyFlexEnd);
  PilatesNodeStyleSetWidth(root, 102);
  PilatesNodeStyleSetHeight(root, 102);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(72, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(82, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(92, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(72, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(82, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(92, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_column_center) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetWidth(root, 102);
  PilatesNodeStyleSetHeight(root, 102);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(36, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(56, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(36, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(56, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_column_space_between) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifySpaceBetween);
  PilatesNodeStyleSetWidth(root, 102);
  PilatesNodeStyleSetHeight(root, 102);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(92, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(92, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_column_space_around) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifySpaceAround);
  PilatesNodeStyleSetWidth(root, 102);
  PilatesNodeStyleSetHeight(root, 102);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(12, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(12, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_row_min_width_and_margin) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetMargin(root, PilatesEdgeLeft, 100);
  PilatesNodeStyleSetMinWidth(root, 50);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 20);
  PilatesNodeStyleSetHeight(root_child0, 20);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(15, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(15, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_row_max_width_and_margin) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetMargin(root, PilatesEdgeLeft, 100);
  PilatesNodeStyleSetWidth(root, 100);
  PilatesNodeStyleSetMaxWidth(root, 80);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 20);
  PilatesNodeStyleSetHeight(root_child0, 20);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_column_min_height_and_margin) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetMargin(root, PilatesEdgeTop, 100);
  PilatesNodeStyleSetMinHeight(root, 50);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 20);
  PilatesNodeStyleSetHeight(root_child0, 20);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(15, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(15, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_colunn_max_height_and_margin) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetMargin(root, PilatesEdgeTop, 100);
  PilatesNodeStyleSetHeight(root, 100);
  PilatesNodeStyleSetMaxHeight(root, 80);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 20);
  PilatesNodeStyleSetHeight(root_child0, 20);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_column_space_evenly) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifySpaceEvenly);
  PilatesNodeStyleSetWidth(root, 102);
  PilatesNodeStyleSetHeight(root, 102);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(18, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(74, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(18, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(46, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(74, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, justify_content_row_space_evenly) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifySpaceEvenly);
  PilatesNodeStyleSetWidth(root, 102);
  PilatesNodeStyleSetHeight(root, 102);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetHeight(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(26, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(51, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(77, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(102, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(77, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(51, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(26, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}
