/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/PilatesFlexWrapTest.html

#include <gtest/gtest.h>
#include <pilates/Pilates.h>

TEST(PilatesTest, wrap_column) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrap);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 30);
  PilatesNodeStyleSetHeight(root_child0, 30);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 30);
  PilatesNodeStyleSetHeight(root_child1, 30);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 30);
  PilatesNodeStyleSetHeight(root_child2, 30);
  PilatesNodeInsertChild(root, root_child2, 2);

  const PilatesNodeRef root_child3 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child3, 30);
  PilatesNodeStyleSetHeight(root_child3, 30);
  PilatesNodeInsertChild(root, root_child3, 3);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child3));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child3));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrap_row) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrap);
  PilatesNodeStyleSetWidth(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 30);
  PilatesNodeStyleSetHeight(root_child0, 30);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 30);
  PilatesNodeStyleSetHeight(root_child1, 30);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 30);
  PilatesNodeStyleSetHeight(root_child2, 30);
  PilatesNodeInsertChild(root, root_child2, 2);

  const PilatesNodeRef root_child3 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child3, 30);
  PilatesNodeStyleSetHeight(root_child3, 30);
  PilatesNodeInsertChild(root, root_child3, 3);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child3));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child3));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrap_row_align_items_flex_end) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignFlexEnd);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrap);
  PilatesNodeStyleSetWidth(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 30);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 30);
  PilatesNodeStyleSetHeight(root_child1, 20);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 30);
  PilatesNodeStyleSetHeight(root_child2, 30);
  PilatesNodeInsertChild(root, root_child2, 2);

  const PilatesNodeRef root_child3 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child3, 30);
  PilatesNodeStyleSetHeight(root_child3, 30);
  PilatesNodeInsertChild(root, root_child3, 3);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child3));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child3));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrap_row_align_items_center) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignCenter);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrap);
  PilatesNodeStyleSetWidth(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 30);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 30);
  PilatesNodeStyleSetHeight(root_child1, 20);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 30);
  PilatesNodeStyleSetHeight(root_child2, 30);
  PilatesNodeInsertChild(root, root_child2, 2);

  const PilatesNodeRef root_child3 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child3, 30);
  PilatesNodeStyleSetHeight(root_child3, 30);
  PilatesNodeInsertChild(root, root_child3, 3);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(5, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child3));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(5, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child3));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, flex_wrap_children_with_min_main_overriding_flex_basis) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrap);
  PilatesNodeStyleSetWidth(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexBasis(root_child0, 50);
  PilatesNodeStyleSetMinWidth(root_child0, 55);
  PilatesNodeStyleSetHeight(root_child0, 50);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexBasis(root_child1, 50);
  PilatesNodeStyleSetMinWidth(root_child1, 55);
  PilatesNodeStyleSetHeight(root_child1, 50);
  PilatesNodeInsertChild(root, root_child1, 1);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(55, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(55, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child1));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(45, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(55, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(45, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(55, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child1));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, flex_wrap_wrap_to_child_height) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root_child0, PilatesFlexDirectionRow);
  PilatesNodeStyleSetAlignItems(root_child0, PilatesAlignFlexStart);
  PilatesNodeStyleSetFlexWrap(root_child0, PilatesWrapWrap);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child0_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child0, 100);
  PilatesNodeInsertChild(root_child0, root_child0_child0, 0);

  const PilatesNodeRef root_child0_child0_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child0_child0, 100);
  PilatesNodeStyleSetHeight(root_child0_child0_child0, 100);
  PilatesNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 100);
  PilatesNodeStyleSetHeight(root_child1, 100);
  PilatesNodeInsertChild(root, root_child1, 1);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child1));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child1));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, flex_wrap_align_stretch_fits_one_row) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrap);
  PilatesNodeStyleSetWidth(root, 150);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 50);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 50);
  PilatesNodeInsertChild(root, root_child1, 1);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child1));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(150, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child1));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrap_reverse_row_align_content_flex_start) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrapReverse);
  PilatesNodeStyleSetWidth(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 30);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 30);
  PilatesNodeStyleSetHeight(root_child1, 20);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 30);
  PilatesNodeStyleSetHeight(root_child2, 30);
  PilatesNodeInsertChild(root, root_child2, 2);

  const PilatesNodeRef root_child3 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child3, 30);
  PilatesNodeStyleSetHeight(root_child3, 40);
  PilatesNodeInsertChild(root, root_child3, 3);

  const PilatesNodeRef root_child4 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child4, 30);
  PilatesNodeStyleSetHeight(root_child4, 50);
  PilatesNodeInsertChild(root, root_child4, 4);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child4));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child4));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrap_reverse_row_align_content_center) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetAlignContent(root, PilatesAlignCenter);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrapReverse);
  PilatesNodeStyleSetWidth(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 30);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 30);
  PilatesNodeStyleSetHeight(root_child1, 20);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 30);
  PilatesNodeStyleSetHeight(root_child2, 30);
  PilatesNodeInsertChild(root, root_child2, 2);

  const PilatesNodeRef root_child3 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child3, 30);
  PilatesNodeStyleSetHeight(root_child3, 40);
  PilatesNodeInsertChild(root, root_child3, 3);

  const PilatesNodeRef root_child4 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child4, 30);
  PilatesNodeStyleSetHeight(root_child4, 50);
  PilatesNodeInsertChild(root, root_child4, 4);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child4));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child4));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrap_reverse_row_single_line_different_size) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrapReverse);
  PilatesNodeStyleSetWidth(root, 300);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 30);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 30);
  PilatesNodeStyleSetHeight(root_child1, 20);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 30);
  PilatesNodeStyleSetHeight(root_child2, 30);
  PilatesNodeInsertChild(root, root_child2, 2);

  const PilatesNodeRef root_child3 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child3, 30);
  PilatesNodeStyleSetHeight(root_child3, 40);
  PilatesNodeInsertChild(root, root_child3, 3);

  const PilatesNodeRef root_child4 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child4, 30);
  PilatesNodeStyleSetHeight(root_child4, 50);
  PilatesNodeInsertChild(root, root_child4, 4);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(300, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(90, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(120, PilatesNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child4));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(300, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(270, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(240, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(210, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(180, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(150, PilatesNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child4));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrap_reverse_row_align_content_stretch) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetAlignContent(root, PilatesAlignStretch);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrapReverse);
  PilatesNodeStyleSetWidth(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 30);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 30);
  PilatesNodeStyleSetHeight(root_child1, 20);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 30);
  PilatesNodeStyleSetHeight(root_child2, 30);
  PilatesNodeInsertChild(root, root_child2, 2);

  const PilatesNodeRef root_child3 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child3, 30);
  PilatesNodeStyleSetHeight(root_child3, 40);
  PilatesNodeInsertChild(root, root_child3, 3);

  const PilatesNodeRef root_child4 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child4, 30);
  PilatesNodeStyleSetHeight(root_child4, 50);
  PilatesNodeInsertChild(root, root_child4, 4);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child4));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child4));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrap_reverse_row_align_content_space_around) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetAlignContent(root, PilatesAlignSpaceAround);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrapReverse);
  PilatesNodeStyleSetWidth(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 30);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 30);
  PilatesNodeStyleSetHeight(root_child1, 20);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 30);
  PilatesNodeStyleSetHeight(root_child2, 30);
  PilatesNodeInsertChild(root, root_child2, 2);

  const PilatesNodeRef root_child3 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child3, 30);
  PilatesNodeStyleSetHeight(root_child3, 40);
  PilatesNodeInsertChild(root, root_child3, 3);

  const PilatesNodeRef root_child4 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child4, 30);
  PilatesNodeStyleSetHeight(root_child4, 50);
  PilatesNodeInsertChild(root, root_child4, 4);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child4));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child4));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrap_reverse_column_fixed_size) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignCenter);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrapReverse);
  PilatesNodeStyleSetWidth(root, 200);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 30);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child1, 30);
  PilatesNodeStyleSetHeight(root_child1, 20);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 30);
  PilatesNodeStyleSetHeight(root_child2, 30);
  PilatesNodeInsertChild(root, root_child2, 2);

  const PilatesNodeRef root_child3 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child3, 30);
  PilatesNodeStyleSetHeight(root_child3, 40);
  PilatesNodeInsertChild(root, root_child3, 3);

  const PilatesNodeRef root_child4 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child4, 30);
  PilatesNodeStyleSetHeight(root_child4, 50);
  PilatesNodeInsertChild(root, root_child4, 4);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(170, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(170, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(170, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(170, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(140, PilatesNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child4));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child3));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child4));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child4));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetWidth(root_child4));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child4));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrapped_row_within_align_items_center) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignCenter);
  PilatesNodeStyleSetWidth(root, 200);
  PilatesNodeStyleSetHeight(root, 200);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root_child0, PilatesFlexDirectionRow);
  PilatesNodeStyleSetFlexWrap(root_child0, PilatesWrapWrap);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child0_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child0, 150);
  PilatesNodeStyleSetHeight(root_child0_child0, 80);
  PilatesNodeInsertChild(root_child0, root_child0_child0, 0);

  const PilatesNodeRef root_child0_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child1, 80);
  PilatesNodeStyleSetHeight(root_child0_child1, 80);
  PilatesNodeInsertChild(root_child0, root_child0_child1, 1);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(160, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(150, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0_child1));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(160, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(150, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(120, PilatesNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0_child1));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrapped_row_within_align_items_flex_start) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignFlexStart);
  PilatesNodeStyleSetWidth(root, 200);
  PilatesNodeStyleSetHeight(root, 200);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root_child0, PilatesFlexDirectionRow);
  PilatesNodeStyleSetFlexWrap(root_child0, PilatesWrapWrap);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child0_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child0, 150);
  PilatesNodeStyleSetHeight(root_child0_child0, 80);
  PilatesNodeInsertChild(root_child0, root_child0_child0, 0);

  const PilatesNodeRef root_child0_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child1, 80);
  PilatesNodeStyleSetHeight(root_child0_child1, 80);
  PilatesNodeInsertChild(root_child0, root_child0_child1, 1);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(160, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(150, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0_child1));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(160, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(150, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(120, PilatesNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0_child1));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrapped_row_within_align_items_flex_end) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignFlexEnd);
  PilatesNodeStyleSetWidth(root, 200);
  PilatesNodeStyleSetHeight(root, 200);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root_child0, PilatesFlexDirectionRow);
  PilatesNodeStyleSetFlexWrap(root_child0, PilatesWrapWrap);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child0_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child0, 150);
  PilatesNodeStyleSetHeight(root_child0_child0, 80);
  PilatesNodeInsertChild(root_child0, root_child0_child0, 0);

  const PilatesNodeRef root_child0_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child1, 80);
  PilatesNodeStyleSetHeight(root_child0_child1, 80);
  PilatesNodeInsertChild(root_child0, root_child0_child1, 1);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(160, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(150, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0_child1));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(160, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(150, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(120, PilatesNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0_child1));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrapped_column_max_height) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetAlignContent(root, PilatesAlignCenter);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignCenter);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrap);
  PilatesNodeStyleSetWidth(root, 700);
  PilatesNodeStyleSetHeight(root, 500);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0, 100);
  PilatesNodeStyleSetHeight(root_child0, 500);
  PilatesNodeStyleSetMaxHeight(root_child0, 200);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetMargin(root_child1, PilatesEdgeLeft, 20);
  PilatesNodeStyleSetMargin(root_child1, PilatesEdgeTop, 20);
  PilatesNodeStyleSetMargin(root_child1, PilatesEdgeRight, 20);
  PilatesNodeStyleSetMargin(root_child1, PilatesEdgeBottom, 20);
  PilatesNodeStyleSetWidth(root_child1, 200);
  PilatesNodeStyleSetHeight(root_child1, 200);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 100);
  PilatesNodeStyleSetHeight(root_child2, 100);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(700, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(250, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(250, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(420, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(700, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(350, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(300, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(250, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(180, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrapped_column_max_height_flex) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetAlignContent(root, PilatesAlignCenter);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignCenter);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrap);
  PilatesNodeStyleSetWidth(root, 700);
  PilatesNodeStyleSetHeight(root, 500);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexGrow(root_child0, 1);
  PilatesNodeStyleSetFlexShrink(root_child0, 1);
  PilatesNodeStyleSetFlexBasisPercent(root_child0, 0);
  PilatesNodeStyleSetWidth(root_child0, 100);
  PilatesNodeStyleSetHeight(root_child0, 500);
  PilatesNodeStyleSetMaxHeight(root_child0, 200);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexGrow(root_child1, 1);
  PilatesNodeStyleSetFlexShrink(root_child1, 1);
  PilatesNodeStyleSetFlexBasisPercent(root_child1, 0);
  PilatesNodeStyleSetMargin(root_child1, PilatesEdgeLeft, 20);
  PilatesNodeStyleSetMargin(root_child1, PilatesEdgeTop, 20);
  PilatesNodeStyleSetMargin(root_child1, PilatesEdgeRight, 20);
  PilatesNodeStyleSetMargin(root_child1, PilatesEdgeBottom, 20);
  PilatesNodeStyleSetWidth(root_child1, 200);
  PilatesNodeStyleSetHeight(root_child1, 200);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child2, 100);
  PilatesNodeStyleSetHeight(root_child2, 100);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(700, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(300, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(180, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(250, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(180, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(300, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(400, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(700, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(300, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(180, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(250, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(180, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(300, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(400, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrap_nodes_with_content_sizing_overflowing_margin) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root, 500);
  PilatesNodeStyleSetHeight(root, 500);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root_child0, PilatesFlexDirectionRow);
  PilatesNodeStyleSetFlexWrap(root_child0, PilatesWrapWrap);
  PilatesNodeStyleSetWidth(root_child0, 85);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child0_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeInsertChild(root_child0, root_child0_child0, 0);

  const PilatesNodeRef root_child0_child0_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child0_child0, 40);
  PilatesNodeStyleSetHeight(root_child0_child0_child0, 40);
  PilatesNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);

  const PilatesNodeRef root_child0_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetMargin(root_child0_child1, PilatesEdgeRight, 10);
  PilatesNodeInsertChild(root_child0, root_child0_child1, 1);

  const PilatesNodeRef root_child0_child1_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child1_child0, 40);
  PilatesNodeStyleSetHeight(root_child0_child1_child0, 40);
  PilatesNodeInsertChild(root_child0_child1, root_child0_child1_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(85, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child1_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(415, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(85, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(45, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(35, PilatesNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child1_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, wrap_nodes_with_content_sizing_margin_cross) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root, 500);
  PilatesNodeStyleSetHeight(root, 500);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root_child0, PilatesFlexDirectionRow);
  PilatesNodeStyleSetFlexWrap(root_child0, PilatesWrapWrap);
  PilatesNodeStyleSetWidth(root_child0, 70);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child0_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeInsertChild(root_child0, root_child0_child0, 0);

  const PilatesNodeRef root_child0_child0_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child0_child0, 40);
  PilatesNodeStyleSetHeight(root_child0_child0_child0, 40);
  PilatesNodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);

  const PilatesNodeRef root_child0_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetMargin(root_child0_child1, PilatesEdgeTop, 10);
  PilatesNodeInsertChild(root_child0, root_child0_child1, 1);

  const PilatesNodeRef root_child0_child1_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child1_child0, 40);
  PilatesNodeStyleSetHeight(root_child0_child1_child0, 40);
  PilatesNodeInsertChild(root_child0_child1, root_child0_child1_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(90, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child1_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(500, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(500, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(430, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(70, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(90, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child0_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child0_child0));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetWidth(root_child0_child1_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0_child1_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}
