/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/PilatesAbsolutePositionTest.html

#include <gtest/gtest.h>
#include <pilates/Pilates.h>

TEST(PilatesTest, absolute_layout_width_height_start_top) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root, 100);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeStart, 10);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeTop, 10);
  PilatesNodeStyleSetWidth(root_child0, 10);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_width_height_end_bottom) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root, 100);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeEnd, 10);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeBottom, 10);
  PilatesNodeStyleSetWidth(root_child0, 10);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_start_top_end_bottom) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root, 100);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeStart, 10);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeTop, 10);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeEnd, 10);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeBottom, 10);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_width_height_start_top_end_bottom) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root, 100);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeStart, 10);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeTop, 10);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeEnd, 10);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeBottom, 10);
  PilatesNodeStyleSetWidth(root_child0, 10);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, do_not_clamp_height_of_absolute_node_to_height_of_its_overflow_hidden_parent) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetOverflow(root, PilatesOverflowHidden);
  PilatesNodeStyleSetWidth(root, 50);
  PilatesNodeStyleSetHeight(root, 50);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeStart, 0);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeTop, 0);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child0_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root_child0_child0, 100);
  PilatesNodeStyleSetHeight(root_child0_child0, 100);
  PilatesNodeInsertChild(root_child0, root_child0_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child0_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(-50, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root_child0_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_within_border) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetMargin(root, PilatesEdgeLeft, 10);
  PilatesNodeStyleSetMargin(root, PilatesEdgeTop, 10);
  PilatesNodeStyleSetMargin(root, PilatesEdgeRight, 10);
  PilatesNodeStyleSetMargin(root, PilatesEdgeBottom, 10);
  PilatesNodeStyleSetPadding(root, PilatesEdgeLeft, 10);
  PilatesNodeStyleSetPadding(root, PilatesEdgeTop, 10);
  PilatesNodeStyleSetPadding(root, PilatesEdgeRight, 10);
  PilatesNodeStyleSetPadding(root, PilatesEdgeBottom, 10);
  PilatesNodeStyleSetBorder(root, PilatesEdgeLeft, 10);
  PilatesNodeStyleSetBorder(root, PilatesEdgeTop, 10);
  PilatesNodeStyleSetBorder(root, PilatesEdgeRight, 10);
  PilatesNodeStyleSetBorder(root, PilatesEdgeBottom, 10);
  PilatesNodeStyleSetWidth(root, 100);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeLeft, 0);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeTop, 0);
  PilatesNodeStyleSetWidth(root_child0, 50);
  PilatesNodeStyleSetHeight(root_child0, 50);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child1, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child1, PilatesEdgeRight, 0);
  PilatesNodeStyleSetPosition(root_child1, PilatesEdgeBottom, 0);
  PilatesNodeStyleSetWidth(root_child1, 50);
  PilatesNodeStyleSetHeight(root_child1, 50);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child2, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child2, PilatesEdgeLeft, 0);
  PilatesNodeStyleSetPosition(root_child2, PilatesEdgeTop, 0);
  PilatesNodeStyleSetMargin(root_child2, PilatesEdgeLeft, 10);
  PilatesNodeStyleSetMargin(root_child2, PilatesEdgeTop, 10);
  PilatesNodeStyleSetMargin(root_child2, PilatesEdgeRight, 10);
  PilatesNodeStyleSetMargin(root_child2, PilatesEdgeBottom, 10);
  PilatesNodeStyleSetWidth(root_child2, 50);
  PilatesNodeStyleSetHeight(root_child2, 50);
  PilatesNodeInsertChild(root, root_child2, 2);

  const PilatesNodeRef root_child3 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child3, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child3, PilatesEdgeRight, 0);
  PilatesNodeStyleSetPosition(root_child3, PilatesEdgeBottom, 0);
  PilatesNodeStyleSetMargin(root_child3, PilatesEdgeLeft, 10);
  PilatesNodeStyleSetMargin(root_child3, PilatesEdgeTop, 10);
  PilatesNodeStyleSetMargin(root_child3, PilatesEdgeRight, 10);
  PilatesNodeStyleSetMargin(root_child3, PilatesEdgeBottom, 10);
  PilatesNodeStyleSetWidth(root_child3, 50);
  PilatesNodeStyleSetHeight(root_child3, 50);
  PilatesNodeInsertChild(root, root_child3, 3);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child3));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child2));

  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetLeft(root_child3));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child3));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetWidth(root_child3));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetHeight(root_child3));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_align_items_and_justify_content_center) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignCenter);
  PilatesNodeStyleSetFlexGrow(root, 1);
  PilatesNodeStyleSetWidth(root, 110);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetWidth(root_child0, 60);
  PilatesNodeStyleSetHeight(root_child0, 40);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(25, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(25, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_align_items_and_justify_content_flex_end) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyFlexEnd);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignFlexEnd);
  PilatesNodeStyleSetFlexGrow(root, 1);
  PilatesNodeStyleSetWidth(root, 110);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetWidth(root_child0, 60);
  PilatesNodeStyleSetHeight(root_child0, 40);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_justify_content_center) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetFlexGrow(root, 1);
  PilatesNodeStyleSetWidth(root, 110);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetWidth(root_child0, 60);
  PilatesNodeStyleSetHeight(root_child0, 40);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_align_items_center) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignCenter);
  PilatesNodeStyleSetFlexGrow(root, 1);
  PilatesNodeStyleSetWidth(root, 110);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetWidth(root_child0, 60);
  PilatesNodeStyleSetHeight(root_child0, 40);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(25, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(25, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_align_items_center_on_child_only) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexGrow(root, 1);
  PilatesNodeStyleSetWidth(root, 110);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignSelf(root_child0, PilatesAlignCenter);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetWidth(root_child0, 60);
  PilatesNodeStyleSetHeight(root_child0, 40);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(25, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(25, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_align_items_and_justify_content_center_and_top_position) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignCenter);
  PilatesNodeStyleSetFlexGrow(root, 1);
  PilatesNodeStyleSetWidth(root, 110);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeTop, 10);
  PilatesNodeStyleSetWidth(root_child0, 60);
  PilatesNodeStyleSetHeight(root_child0, 40);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(25, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(25, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_align_items_and_justify_content_center_and_bottom_position) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignCenter);
  PilatesNodeStyleSetFlexGrow(root, 1);
  PilatesNodeStyleSetWidth(root, 110);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeBottom, 10);
  PilatesNodeStyleSetWidth(root_child0, 60);
  PilatesNodeStyleSetHeight(root_child0, 40);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(25, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(25, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(50, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_align_items_and_justify_content_center_and_left_position) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignCenter);
  PilatesNodeStyleSetFlexGrow(root, 1);
  PilatesNodeStyleSetWidth(root, 110);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeLeft, 5);
  PilatesNodeStyleSetWidth(root_child0, 60);
  PilatesNodeStyleSetHeight(root_child0, 40);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(5, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(5, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_align_items_and_justify_content_center_and_right_position) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetJustifyContent(root, PilatesJustifyCenter);
  PilatesNodeStyleSetAlignItems(root, PilatesAlignCenter);
  PilatesNodeStyleSetFlexGrow(root, 1);
  PilatesNodeStyleSetWidth(root, 110);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPosition(root_child0, PilatesEdgeRight, 5);
  PilatesNodeStyleSetWidth(root_child0, 60);
  PilatesNodeStyleSetHeight(root_child0, 40);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(45, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(110, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(45, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(30, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(40, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, position_root_with_rtl_should_position_withoutdirection) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPosition(root, PilatesEdgeLeft, 72);
  PilatesNodeStyleSetWidth(root, 52);
  PilatesNodeStyleSetHeight(root, 52);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(72, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(52, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(52, PilatesNodeLayoutGetHeight(root));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(72, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(52, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(52, PilatesNodeLayoutGetHeight(root));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_percentage_bottom_based_on_parent_height) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetWidth(root, 100);
  PilatesNodeStyleSetHeight(root, 200);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPositionPercent(root_child0, PilatesEdgeTop, 50);
  PilatesNodeStyleSetWidth(root_child0, 10);
  PilatesNodeStyleSetHeight(root_child0, 10);
  PilatesNodeInsertChild(root, root_child0, 0);

  const PilatesNodeRef root_child1 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child1, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPositionPercent(root_child1, PilatesEdgeBottom, 50);
  PilatesNodeStyleSetWidth(root_child1, 10);
  PilatesNodeStyleSetHeight(root_child1, 10);
  PilatesNodeInsertChild(root, root_child1, 1);

  const PilatesNodeRef root_child2 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child2, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetPositionPercent(root_child2, PilatesEdgeTop, 10);
  PilatesNodeStyleSetPositionPercent(root_child2, PilatesEdgeBottom, 10);
  PilatesNodeStyleSetWidth(root_child2, 10);
  PilatesNodeInsertChild(root, root_child2, 2);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(90, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(160, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(200, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(90, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(90, PilatesNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(90, PilatesNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(90, PilatesNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(10, PilatesNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(160, PilatesNodeLayoutGetHeight(root_child2));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_in_wrap_reverse_column_container) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrapReverse);
  PilatesNodeStyleSetWidth(root, 100);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetWidth(root_child0, 20);
  PilatesNodeStyleSetHeight(root_child0, 20);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_in_wrap_reverse_row_container) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrapReverse);
  PilatesNodeStyleSetWidth(root, 100);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetWidth(root_child0, 20);
  PilatesNodeStyleSetHeight(root_child0, 20);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_in_wrap_reverse_column_container_flex_end) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrapReverse);
  PilatesNodeStyleSetWidth(root, 100);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignSelf(root_child0, PilatesAlignFlexEnd);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetWidth(root_child0, 20);
  PilatesNodeStyleSetHeight(root_child0, 20);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}

TEST(PilatesTest, absolute_layout_in_wrap_reverse_row_container_flex_end) {
  const PilatesConfigRef config = PilatesConfigNew();

  const PilatesNodeRef root = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetFlexDirection(root, PilatesFlexDirectionRow);
  PilatesNodeStyleSetFlexWrap(root, PilatesWrapWrapReverse);
  PilatesNodeStyleSetWidth(root, 100);
  PilatesNodeStyleSetHeight(root, 100);

  const PilatesNodeRef root_child0 = PilatesNodeNewWithConfig(config);
  PilatesNodeStyleSetAlignSelf(root_child0, PilatesAlignFlexEnd);
  PilatesNodeStyleSetPositionType(root_child0, PilatesPositionTypeAbsolute);
  PilatesNodeStyleSetWidth(root_child0, 20);
  PilatesNodeStyleSetHeight(root_child0, 20);
  PilatesNodeInsertChild(root, root_child0, 0);
  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionLTR);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeCalculateLayout(root, PilatesUndefined, PilatesUndefined, PilatesDirectionRTL);

  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, PilatesNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(80, PilatesNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, PilatesNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, PilatesNodeLayoutGetHeight(root_child0));

  PilatesNodeFreeRecursive(root);

  PilatesConfigFree(config);
}
